### ISSUE TITLE
Add deep eql support

### ISSUE THREAD

**Issue by fragonib** [kwirke/maybe-chai#1]
Great library.

Could you add deep equal support? Something like this:

```js
    const result = S.Just([]);
    expect(result).to.be.just([]);
```

Now assertion result on `false`

**Comment by pinyotensor** [comment]
Hi @fragonib ,

I'm glad you are finding this lib useful! I've just uploaded **version 2.0.0 that automatically deep equals** Just values.

The reason is that I think deep equaling is the default use case when comparing Maybe contents, and also the chai-like `deep` syntax really breaks the sentence readability:
```javascript
expect(Just([])).to.be.deep.just([]) // Wat
expect(Just([])).to.deep.just([]) // WAT
```
The current syntax just feels natural. Furthermore, shallow equaling is still possible using chaining:
```javascript
const test = {a: 1}
expect(Just(test)).to.be.just().and.equal(test) // Ok!
expect(Just(test)).to.be.just().and.equal({a: 1}) // Fails as expected
```

Therefore, I'm closing this issue. Cheers!
